name: Python 3.12 CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3
      
      - name: Install dependencies
        run: |
          make install
      
      - name: Lint
        run: |
          make lint
      
      - name: Test
        run: |
          make test
